#!/bin/bash
FILE_PATH=$(jq -r '.tool_input.file_path' < /dev/stdin)

if echo "$FILE_PATH" | grep -q 'manifest\.toml$'; then
  echo '{"decision":"block","reason":"manifest.toml is auto-generated by gleam deps download. Do not edit directly."}'
  exit 0
fi

exit 0
