changesDir: .changes
unreleasedDir: unreleased
headerPath: header.md
changelogPath: CHANGELOG.md
versionHeaderPath: ""
versionFooterPath: ""
versionExt: md
envPrefix: CHANGIE
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
changeFormat: |-
    #### {{(splitn "\n" 2 .Body)._0}}
    {{with (splitn "\n" 2 .Body)._1 | default "" | trim}}
    {{.}}
    {{end}}
body:
    block: true
    minLength: 1
newlines:
    afterChangelogHeader: 1
    afterChangelogVersion: 1
    afterVersion: 1
    endOfVersion: 1
