changesDir: .changes
unreleasedDir: unreleased
headerPath: header.md
changelogPath: CHANGELOG.md
versionHeaderPath: ""
versionFooterPath: ""
versionExt: md
envPrefix: CHANGIE

projectsVersionSeparator: "-"

projects:
    - label: vestibule
      key: vestibule
      changelog: CHANGELOG.md
    - label: vestibule_apple
      key: vestibule_apple
      changelog: packages/vestibule_apple/CHANGELOG.md
    - label: vestibule_google
      key: vestibule_google
      changelog: packages/vestibule_google/CHANGELOG.md
    - label: vestibule_microsoft
      key: vestibule_microsoft
      changelog: packages/vestibule_microsoft/CHANGELOG.md
    - label: vestibule_wisp
      key: vestibule_wisp
      changelog: packages/vestibule_wisp/CHANGELOG.md

versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '#### {{.Kind}}'
changeFormat: |-
    ##### {{(splitn "\n" 2 .Body)._0}}
    {{with (splitn "\n" 2 .Body)._1 | default "" | trim}}
    {{.}}
    {{end}}
body:
    block: true
    minLength: 1
kinds:
    - label: Added
      auto: minor
    - label: Changed
      auto: patch
    - label: Deprecated
      auto: patch
    - label: Fixed
      auto: patch
    - label: Performance
      auto: patch
    - label: Removed
      auto: patch
    - label: Reverted
      auto: patch
    - label: Dependencies
      auto: patch
    - label: Security
      auto: patch
newlines:
    afterChangelogHeader: 1
    afterChangelogVersion: 1
    afterKind: 1
    afterVersion: 1
    beforeKind: 1
    endOfVersion: 1
