//// OAuth client configuration and per-authorization request options.

import gleam/dict.{type Dict}
import gleam/list
import vestibule/error.{type AuthError}

/// OAuth client authentication method.
pub type ClientAuth {
  PublicClient
  ClientSecret(String)
  ClientAssertion(String)
}

/// Durable OAuth client configuration.
pub opaque type ClientConfig {
  ClientConfig(client_id: String, redirect_uri: String, auth: ClientAuth)
}

/// Per-authorization request options.
pub opaque type AuthorizeOptions {
  AuthorizeOptions(scopes: List(String), extra_params: Dict(String, String))
}

/// Create durable client configuration.
pub fn new(
  client_id client_id: String,
  redirect_uri redirect_uri: String,
  auth auth: ClientAuth,
) -> ClientConfig {
  ClientConfig(client_id: client_id, redirect_uri: redirect_uri, auth: auth)
}

/// Return the configured OAuth client ID.
pub fn client_id(config: ClientConfig) -> String {
  config.client_id
}

/// Return the redirect URI registered with the provider.
pub fn redirect_uri(config: ClientConfig) -> String {
  config.redirect_uri
}

/// Return the configured OAuth client authentication method.
pub fn client_auth(config: ClientConfig) -> ClientAuth {
  config.auth
}

/// Return a client secret value when the authentication method provides one.
pub fn client_secret(config: ClientConfig) -> Result(String, AuthError(e)) {
  case config.auth {
    ClientSecret(secret) -> Ok(secret)
    PublicClient | ClientAssertion(_) ->
      Error(error.config(
        reason: "Client authentication does not provide a client_secret",
      ))
  }
}

/// Create empty per-authorization request options.
pub fn authorize_options() -> AuthorizeOptions {
  AuthorizeOptions(scopes: [], extra_params: dict.new())
}

/// Set custom scopes for an authorization request, replacing any defaults.
pub fn with_scopes(
  options: AuthorizeOptions,
  scopes: List(String),
) -> AuthorizeOptions {
  AuthorizeOptions(..options, scopes: scopes)
}

/// Add extra query parameters to an authorization request, merging them into
/// any previously added parameters. Later values win on duplicate keys.
///
/// Reserved OAuth authorization parameters are rejected so callers cannot
/// override values generated by Vestibule or provider strategies.
pub fn with_extra_params(
  options: AuthorizeOptions,
  params: List(#(String, String)),
) -> Result(AuthorizeOptions, AuthError(e)) {
  case find_reserved_param(params) {
    Ok(param) ->
      Error(error.config(
        reason: "Reserved authorization parameter not allowed: " <> param,
      ))
    Error(Nil) ->
      Ok(
        AuthorizeOptions(
          ..options,
          extra_params: dict.merge(options.extra_params, dict.from_list(params)),
        ),
      )
  }
}

/// Return configured per-request scopes.
pub fn scopes(options: AuthorizeOptions) -> List(String) {
  options.scopes
}

/// Return configured extra authorization query parameters.
pub fn extra_params(options: AuthorizeOptions) -> Dict(String, String) {
  options.extra_params
}

fn find_reserved_param(params: List(#(String, String))) -> Result(String, Nil) {
  case params {
    [] -> Error(Nil)
    [#(key, _), ..rest] ->
      case list.contains(reserved_authorization_params(), key) {
        True -> Ok(key)
        False -> find_reserved_param(rest)
      }
  }
}

fn reserved_authorization_params() -> List(String) {
  [
    "response_type",
    "client_id",
    "redirect_uri",
    "scope",
    "state",
    "code_challenge",
    "code_challenge_method",
    "nonce",
    "response_mode",
  ]
}
