//// Apple Sign In strategy for vestibule.
////
//// Apple's OAuth implementation has several key differences from standard providers:
////
//// - **No userinfo endpoint**: User info is extracted from the `id_token` JWT
////   in the token response rather than from a separate API call.
//// - **`response_mode=form_post`**: Apple sends the callback as a POST with
////   form data. The vestibule core handles extracting callback params, so this
////   strategy just adds the parameter to the authorization URL.
//// - **Client secret is a JWT**: Apple requires the client_secret to be a signed
////   JWT. Until this strategy supports a dedicated client assertion mode, the
////   caller generates this JWT and provides it as `config.ClientSecret(jwt)`.
////   This strategy passes it through to the token endpoint.
//// - **User info only on first auth**: Apple only sends the full user object
////   (with name) on the first authorization. Subsequent authorizations only
////   include `sub` and `email` in the ID token.
//// - **JWT signature verification**: ID tokens are verified against Apple's
////   published JWKS keys using ES256.
////
//// ## Setup
////
//// Call `vestibule_apple.try_init()` once per VM at application startup to
//// initialize caches, then use `vestibule_apple.strategy()` to create the
//// strategy. Handle the error, or assert at the top level of your
//// application where failing to start is the right outcome:
////
//// ```gleam
//// let assert Ok(apple) = vestibule_apple.try_init()
//// let strategy = vestibule_apple.strategy(apple)
//// ```

import gleam/dict
import gleam/dynamic
import gleam/dynamic/decode
import gleam/json
import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/result
import gleam/string
import gleam/time/duration
import gleam/uri

import gleam/http/request
import gleam/http/response
import gleam/httpc

import glow_auth
import glow_auth/authorize_uri
import glow_auth/token_request
import glow_auth/uri/uri_builder

import vestibule/config.{type AuthorizeOptions, type ClientConfig}
import vestibule/credentials
import vestibule/error.{type AuthError}
import vestibule/logger
import vestibule/provider_support
import vestibule/strategy.{type ExchangeResult, type Strategy, type UserResult}
import vestibule/user_info
import vestibule_apple/jwks.{type JwksCache}
import vestibule_apple/jwt
import ywt/claim
import ywt/verify_key.{type VerifyKey}

/// Holds the JWKS cache used for Apple ID token signature verification.
/// Returned by `try_init()` and required by `strategy()`. Construction and
/// field access are intentionally opaque so the cache backing store can change
/// without breaking consumers.
pub opaque type AppleCache {
  AppleCache(jwks: JwksCache)
}

/// Errors returned by checked Apple cache initialization.
pub type AppleInitError {
  JwksCacheInitFailed(jwks.JwksCacheError)
}

/// Try to initialize the Apple strategy's caches.
///
/// Must be called once per VM at application startup before handling any
/// authentication flows. Returns the cache handle needed by `strategy()`,
/// or an error if the underlying cache tables already exist or cannot be
/// created.
///
/// ## Example
///
/// ```gleam
/// let assert Ok(apple) = vestibule_apple.try_init()
/// let strategy = vestibule_apple.strategy(apple)
/// ```
pub fn try_init() -> Result(AppleCache, AppleInitError) {
  try_init_named("vestibule_apple")
}

/// Try to initialize named Apple strategy caches. Useful for tests that need
/// isolated cache tables.
pub fn try_init_named(prefix: String) -> Result(AppleCache, AppleInitError) {
  case jwks.try_init_named(prefix <> "_jwks") {
    Ok(jwks) -> Ok(AppleCache(jwks: jwks))
    Error(err) -> Error(JwksCacheInitFailed(err))
  }
}

/// Create an Apple Sign In authentication strategy.
///
/// Requires the cache handle from `try_init()`. Apple requires
/// `response_mode=form_post` for the authorization URL, which is added
/// automatically. The `config.ClientSecret(jwt)` value must be a signed JWT
/// generated by the caller (see Apple's documentation).
///
/// ID tokens are verified against Apple's published JWKS keys with
/// claim validation for issuer, audience, and expiration.
pub fn strategy(apple: AppleCache) -> Strategy(e) {
  strategy.new(
    provider: "apple",
    default_scopes: ["name", "email"],
    authorize_url: do_authorize_url,
    exchange_code: fn(config, code, code_verifier) {
      do_exchange_code(config, code, code_verifier)
    },
    fetch_user: fn(config, exchange) { do_fetch_user(apple, config, exchange) },
  )
  |> strategy.with_nonce()
  |> strategy.with_refresh(do_refresh_token)
}

/// Parse Apple token response JSON.
///
/// Apple's token response includes an `id_token` JWT containing user claims.
/// This function parses the response and returns standard credentials plus
/// provider-specific artifacts such as the raw `id_token`.
pub fn parse_token_response(
  body: String,
) -> Result(ExchangeResult, AuthError(e)) {
  do_parse_token_response(body, "token")
}

fn do_parse_token_response(
  body: String,
  endpoint: String,
) -> Result(ExchangeResult, AuthError(e)) {
  let result = {
    use body <- result.try(provider_support.check_token_error(body))
    parse_success_token(body)
  }
  case result {
    Ok(exchange) -> {
      let has_id_token =
        dict.has_key(strategy.exchange_artifacts(exchange), "id_token")
      let id_token_fields = case has_id_token {
        True -> [logger.bool_field("has_id_token", True)]
        False -> []
      }
      logger.new(
        level: logger.Debug,
        event: "vestibule.provider.token_parse.success",
        phase: "provider_request",
        outcome: "success",
        provider: Some("apple"),
        fields: list.flatten([
          [
            logger.field("endpoint", endpoint),
            logger.bool_field(
              "has_refresh_token",
              option.is_some(
                credentials.refresh_token(strategy.exchange_credentials(
                  exchange,
                )),
              ),
            ),
            logger.int_field(
              "scope_count",
              list.length(
                credentials.scopes(strategy.exchange_credentials(exchange)),
              ),
            ),
          ],
          id_token_fields,
        ]),
      )
      |> logger.emit()
      Ok(exchange)
    }
    Error(err) -> {
      logger.new(
        level: logger.Warning,
        event: "vestibule.provider.token_parse.failure",
        phase: "provider_request",
        outcome: "failure",
        provider: Some("apple"),
        fields: [
          logger.field("endpoint", endpoint),
          logger.field("error_category", logger.auth_error_category(err)),
        ],
      )
      |> logger.emit()
      Error(err)
    }
  }
}

fn parse_success_token(body: String) -> Result(ExchangeResult, AuthError(e)) {
  let decoder = {
    use access_token <- decode.field("access_token", decode.string)
    use token_type <- decode.field("token_type", decode.string)
    use expires_in <- decode.optional_field(
      "expires_in",
      None,
      decode.optional(decode.int),
    )
    use refresh_token <- decode.optional_field(
      "refresh_token",
      None,
      decode.optional(decode.string),
    )
    use id_token <- decode.optional_field(
      "id_token",
      None,
      decode.optional(decode.string),
    )
    use scope <- decode.optional_field("scope", "", decode.string)
    let scopes = case scope {
      "" -> []
      s -> string.split(s, " ")
    }
    decode.success(#(
      credentials.new(
        token: access_token,
        refresh_token: refresh_token,
        token_type: token_type,
        expires_in: expires_in,
        scopes: scopes,
      ),
      id_token,
    ))
  }
  case json.parse(body, decoder) {
    Ok(#(credentials, id_token)) ->
      Ok(strategy.exchange_result_with_artifacts(
        credentials,
        id_token_artifacts(id_token),
      ))
    _ ->
      Error(error.code_exchange(reason: "Failed to parse Apple token response"))
  }
}

fn id_token_artifacts(
  id_token: Option(String),
) -> dict.Dict(String, dynamic.Dynamic) {
  case id_token {
    Some(token) -> dict.from_list([#("id_token", dynamic.string(token))])
    None -> dict.new()
  }
}

/// Verify and decode an Apple ID token JWT.
///
/// Fetches Apple's JWKS public keys (cached), verifies the JWT signature
/// using ES256, and validates the `iss`, `aud`, and `exp` claims.
///
/// Returns the user's `sub` (uid) and `UserInfo` on success.
pub fn verify_id_token(
  jwt jwt: String,
  keys keys: List(VerifyKey),
  client_id client_id: String,
) -> Result(#(String, user_info.UserInfo), AuthError(e)) {
  let claims = [
    claim.issuer("https://appleid.apple.com", []),
    claim.audience(client_id, []),
    claim.expires_at(
      max_age: duration.minutes(10),
      leeway: duration.seconds(60),
    ),
  ]

  let payload_decoder = {
    use sub <- decode.field("sub", decode.string)
    use email <- decode.optional_field(
      "email",
      None,
      decode.optional(decode.string),
    )
    use email_verified <- decode.optional_field(
      "email_verified",
      None,
      decode.optional(flexible_email_verified_decoder()),
    )
    decode.success(#(sub, email, email_verified))
  }

  case
    jwt.decode(jwt: jwt, using: payload_decoder, claims: claims, keys: keys)
  {
    Ok(#(sub, email, email_verified)) -> {
      let verified_email = case email, email_verified {
        Some(addr), Some(True) -> Some(addr)
        _, _ -> None
      }
      Ok(#(
        sub,
        user_info.new()
          |> user_info.with_email(verified_email)
          |> user_info.with_nickname(email),
      ))
    }
    Error(jwt.InvalidSignature) | Error(jwt.NoMatchingKey) ->
      Error(error.user_info(
        reason: "Apple ID token signature verification failed",
      ))
    Error(jwt.TokenExpired(_)) ->
      Error(error.user_info(reason: "Apple ID token has expired"))
    Error(jwt.InvalidIssuer(_, _)) ->
      Error(error.user_info(reason: "Apple ID token issuer is invalid"))
    Error(jwt.InvalidAudience(_, _)) ->
      Error(error.user_info(
        reason: "Apple ID token audience does not match client_id",
      ))
    Error(_) ->
      Error(error.user_info(reason: "Failed to verify Apple ID token"))
  }
}

/// Decoder that handles email_verified as either a boolean or a string.
/// Apple sends email_verified as a string "true"/"false" in some cases
/// and as a boolean in others.
fn flexible_email_verified_decoder() -> decode.Decoder(Bool) {
  decode.one_of(decode.bool, [string_bool_decoder()])
}

fn string_bool_decoder() -> decode.Decoder(Bool) {
  decode.string
  |> decode.then(fn(s) {
    case s {
      "true" -> decode.success(True)
      _ -> decode.success(False)
    }
  })
}

// Calls check_response_status_for_endpoint (emitting structured logs) but
// maps HttpKind back to NetworkKind behavior to preserve Apple strategy
// behavior from before the HTTP error kind existed.
fn check_apple_http(
  response: response.Response(String),
  endpoint: String,
) -> Result(String, AuthError(e)) {
  provider_support.check_response_status_for_endpoint(
    response,
    provider_name: "apple",
    endpoint: endpoint,
  )
  |> result.map_error(fn(err) {
    case error.kind(err) {
      error.HttpKind -> error.network(reason: error.message(err))
      _ -> err
    }
  })
}

fn do_authorize_url(
  client_config: ClientConfig,
  options: AuthorizeOptions,
  scopes: List(String),
  state: String,
) -> Result(String, AuthError(e)) {
  use site <- result.try(
    uri.parse("https://appleid.apple.com")
    |> result.map_error(fn(_) {
      error.config(reason: "Failed to parse Apple OAuth base URL")
    }),
  )
  use redirect <- result.try(
    provider_support.parse_redirect_uri(config.redirect_uri(client_config)),
  )
  let client =
    glow_auth.Client(
      id: config.client_id(client_config),
      secret: "",
      site: site,
    )
  let url =
    authorize_uri.build(
      client,
      uri_builder.RelativePath("/auth/authorize"),
      redirect,
    )
    |> authorize_uri.set_scope(string.join(scopes, " "))
    |> authorize_uri.set_state(state)
    |> authorize_uri.to_code_authorization_uri()
    |> uri.to_string()
  // Add response_mode=form_post (Apple requires this)
  let url = url <> "&response_mode=form_post"
  // Append any extra params from options
  let url =
    provider_support.append_query_params(
      url,
      dict.to_list(config.extra_params(options)),
    )
  Ok(url)
}

fn do_exchange_code(
  client_config: ClientConfig,
  code: String,
  code_verifier: Option(String),
) -> Result(ExchangeResult, AuthError(e)) {
  use site <- result.try(
    uri.parse("https://appleid.apple.com")
    |> result.map_error(fn(_) {
      error.config(reason: "Failed to parse Apple OAuth base URL")
    }),
  )
  use redirect <- result.try(
    provider_support.parse_redirect_uri(config.redirect_uri(client_config)),
  )
  use client_secret <- result.try(config.client_secret(client_config))
  let client =
    glow_auth.Client(
      id: config.client_id(client_config),
      secret: client_secret,
      site: site,
    )
  let req =
    token_request.authorization_code(
      client,
      uri_builder.RelativePath("/auth/token"),
      code,
      redirect,
    )
    |> request.set_header("accept", "application/json")
  let req = strategy.append_code_verifier(req, code_verifier)
  logger.new(
    level: logger.Debug,
    event: "vestibule.provider.request.start",
    phase: "provider_request",
    outcome: "start",
    provider: Some("apple"),
    fields: [logger.field("endpoint", "token")],
  )
  |> logger.emit()
  case httpc.send(req) {
    Ok(response) -> {
      use body <- result.try(check_apple_http(response, "token"))
      parse_token_response(body)
    }
    Error(_) -> {
      logger.new(
        level: logger.Error,
        event: "vestibule.provider.request.failure",
        phase: "provider_request",
        outcome: "failure",
        provider: Some("apple"),
        fields: [
          logger.field("endpoint", "token"),
          logger.field("error_category", "network_error"),
        ],
      )
      |> logger.emit()
      Error(error.network(reason: "Failed to connect to Apple token endpoint"))
    }
  }
}

fn do_refresh_token(
  client_config: ClientConfig,
  refresh_token: String,
) -> Result(credentials.Credentials, AuthError(e)) {
  use site <- result.try(
    uri.parse("https://appleid.apple.com")
    |> result.map_error(fn(_) {
      error.config(reason: "Failed to parse Apple OAuth base URL")
    }),
  )
  use client_secret <- result.try(config.client_secret(client_config))
  let client =
    glow_auth.Client(
      id: config.client_id(client_config),
      secret: client_secret,
      site: site,
    )
  let req =
    token_request.refresh(
      client,
      uri_builder.RelativePath("/auth/token"),
      refresh_token,
    )
    |> request.set_header("accept", "application/json")

  logger.new(
    level: logger.Debug,
    event: "vestibule.provider.request.start",
    phase: "provider_request",
    outcome: "start",
    provider: Some("apple"),
    fields: [logger.field("endpoint", "refresh")],
  )
  |> logger.emit()
  case httpc.send(req) {
    Ok(response) -> {
      use body <- result.try(
        provider_support.check_response_status_for_endpoint(
          response,
          provider_name: "apple",
          endpoint: "refresh",
        ),
      )
      use exchange <- result.try(do_parse_token_response(body, "refresh"))
      Ok(strategy.exchange_credentials(exchange))
    }
    Error(_) -> {
      logger.new(
        level: logger.Error,
        event: "vestibule.provider.request.failure",
        phase: "provider_request",
        outcome: "failure",
        provider: Some("apple"),
        fields: [
          logger.field("endpoint", "refresh"),
          logger.field("error_category", "network_error"),
        ],
      )
      |> logger.emit()
      Error(error.network(reason: "Failed to connect to Apple token endpoint"))
    }
  }
}

fn do_fetch_user(
  apple: AppleCache,
  client_config: ClientConfig,
  exchange: ExchangeResult,
) -> Result(UserResult, AuthError(e)) {
  // Apple has no userinfo endpoint. User info comes from the id_token JWT
  // returned as an exchange artifact.
  use artifact <- result.try(
    dict.get(strategy.exchange_artifacts(exchange), "id_token")
    |> result.replace_error(error.user_info(
      reason: "No Apple ID token found in exchange artifacts.",
    )),
  )
  use id_token <- result.try(
    decode.run(artifact, decode.string)
    |> result.map_error(fn(_) {
      error.user_info(reason: "Apple ID token artifact is not a string")
    }),
  )
  use keys <- result.try(jwks.get_keys(apple.jwks))
  use #(uid, info) <- result.try(verify_id_token(
    jwt: id_token,
    keys: keys,
    client_id: config.client_id(client_config),
  ))
  Ok(strategy.user_result(uid: uid, info: info, extra: dict.new()))
}
