name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  checks:
    name: Checks
    uses: tylerbutler/actions/.github/workflows/gleam-workspace-ci.yml@1b043450f1919503d6c23e3ada9fc7aaa4e2a99b # ratchet:tylerbutler/actions/.github/workflows/gleam-workspace-ci.yml@main
    with:
      cache: true

  docs:
    name: Docs
    uses: tylerbutler/actions/.github/workflows/gleam-workspace-ci.yml@1b043450f1919503d6c23e3ada9fc7aaa4e2a99b # ratchet:tylerbutler/actions/.github/workflows/gleam-workspace-ci.yml@main
    with:
      cache: true
      format-check: false
      check: false
      build-strict: false
      test: false
      docs: true
